### ISSUE TITLE
why syn scan need root privilege?

### ISSUE THREAD

**Issue by qahehe** [JustinTimperio/gomap#8]
I don't know why gomap stealth scan need root privilege, my WSL ubuntu root can't find go command, should I reinstall go?
<img width="437" alt="Snipaste_2021-08-31_15-44-16" src="https://user-images.githubusercontent.com/25258443/131463589-fc7068bb-ce26-4e9a-9348-73f7f7ac4b23.png">

**Comment by qahehe** [comment]
update:
i get root privilege but it still can't work
<img width="615" alt="Snipaste_2021-08-31_15-57-37" src="https://user-images.githubusercontent.com/25258443/131465172-b2307dfd-5488-4339-a05a-e00b0a849af7.png">

**Comment by JustinTimperio** [comment]
To answer your question, stealth scans require directly attaching to and reading all packets sent to the interface. This is required for security reasons so only users with Sudo access it. 

As for why it's not working in a WSL environment I'm not totally sure. Do you have go 1.16 or 1.17?

**Comment by qahehe** [comment]
> To answer your question, stealth scans require directly attaching to and reading all packets sent to the interface. This is required for security reasons so only users with Sudo access it.
> 
> As for why it's not working in a WSL environment I'm not totally sure. Do you have go 1.16 or 1.17?

hello，i am glad to see reply from you.i change wsl to Goland  in windows 10  ,my go environment 1.16.7 
here is my  running result :
<img width="507" alt="Snipaste_2021-08-31_21-51-29" src="https://user-images.githubusercontent.com/25258443/131514961-69b976b4-1815-48ae-b39f-d8c7162c0d81.png">

**Comment by JustinTimperio** [comment]
So looking at the error, these seem to be issues with not being able to bind to the interface within WSL. Try taking the binary out of WSL and executing the EXE on the primary system.

**Comment by qahehe** [comment]
> So looking at the error, these seem to be issues with not being able to bind to the interface within WSL. Try taking the binary out of WSL and executing the EXE on the primary system.

I may agree with you , I think WSL restrain the bind of socket, but why I can't bind in windows10  in administrator  cmd?  I go mod tidy in windows 10 , but it seems still not work,  maybe I should build an exe on primary linux?

**Comment by JustinTimperio** [comment]
So I can't say I have really tested this a lot on windows but I would recommend building the binaries on Linux, then transferring them precompiled to the target.  You could use docker to build as well.

**Comment by qahehe** [comment]
I finally run it without exception in ubuntu16.04 LTS ,but I found fastscan whether it is true or false result in different  consequence.maybe it is just a network problem?   but anyway ,thank you for your help ,have a good time!
<img width="364" alt="Snipaste_2021-09-01_10-12-34" src="https://user-images.githubusercontent.com/25258443/131600511-4d8b21d5-6dd8-4162-8147-71ca562e9c0a.png">

**Comment by JustinTimperio** [comment]
This is partially intentional. FastScan only scans the most common ports for speed's sake. It is a bit odd that it's not seeing 443. I may need to tune down the speed so it doesn't miss stuff like that. The deadline for response is fairly short.
