### ISSUE TITLE
[Feature Request] Support for Proxy?

### ISSUE THREAD

**Issue by cogitoergosumsw** [JustinTimperio/gomap#9]
is it possible to support proxy dialer instead? for HTTP and SOCKS5

**Comment by JustinTimperio** [comment]
Probably :D 
I don't really have time to try and implement this but I'm happy to take PR's.

**Comment by cogitoergosumsw** [comment]
#13 ok done! pls help to look through the PR :)

**Comment by taigrr** [comment]
Closeable?

**Comment by JustinTimperio** [comment]
I apologize for the massive delays here. The man issue if you want to check out PR is version control and not breaking down stream repos. I will close this when i merge the dev branch and sort version control
